### PR TITLE
Add cs and static analysis files to .gitattributes

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi @nikolaposa, some files were missing in the gitattributes definition

### CODE REVIEW

**Comment by nikolaposa** [comment]
Thanks!

**Comment by VincentLanglet** [comment]
You're welcome.
Since there are not release often recently (last one is 3 years old), do you think it would be worth a patch release ?

**Comment by nikolaposa** [comment]
Yeah, not ideal to make a release because of a single change. I'll give it a week or two if someone else sends something (although I doubt it), then I will make a release.

**Comment by szepeviktor** [comment]
Here is all my goodies to keep an eye 👁️ on these problem on **every** commit.
https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows

The [check for exported files](https://github.com/nikolaposa/version/pull/37) is the last step in the workflow called _Integrity_.

**Pull request merged**
